time: &time 250
dt: &dt 1.0
name: 
training:
  task: 'MNIST'
  data_dir: './data'
  log_dir: './logs'
  intensity: 128
  n_classes: 10
  batch_size: 8
  seed: 1234
  n_neurons: 100
  input_size: 28
  reduction: 'max'
  theta_plus: .05
  epochs: 1
  inh: 120
encoder: 
  module_name: bindsnet.encoding
  class_name: PoissonEncoder
  params:
    time: *time
    dt: *dt
